# Generated by Django 5.2.4 on 2025-09-16 16:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do modelo de IA (ex: 'gemini-2.5-flash-preview').", max_length=100, unique=True)),
                ('provedor', models.CharField(help_text='O provedor ou empresa responsável pelo modelo.', max_length=50)),
                ('contexto_max', models.PositiveIntegerField(default=0, help_text="O número máximo de tokens que o modelo pode 'lembrar'.")),
                ('custo_input_mil_tokens', models.DecimalField(decimal_places=6, default=0.0, help_text='Custo estimado por 1000 tokens de entrada (em dólares).', max_digits=8)),
                ('custo_output_mil_tokens', models.DecimalField(decimal_places=6, default=0.0, help_text='Custo estimado por 1000 tokens de saída (em dólares).', max_digits=8)),
                ('ativo', models.BooleanField(default=True, help_text='Se este modelo está ativo e disponível para uso.')),
            ],
            options={
                'verbose_name': 'modelo de IA',
                'verbose_name_plural': 'modelos de IA',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PersonalidadeIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome identificador da personalidade (ex: 'assistente', 'criativo').", max_length=50, unique=True)),
                ('descricao', models.CharField(help_text='Descrição breve da personalidade e seu comportamento.', max_length=255)),
                ('prompt_sistema', models.TextField(help_text="Instrução do sistema para guiar a personalidade da IA. Ex: 'Você é um assistente prestativo...'")),
                ('alinhamento', models.CharField(help_text="Alinhamento comportamental da IA (ex: 'ALINHADO', 'NEUTRO_MAL').", max_length=50)),
                ('tom', models.TextField(help_text="Tom de voz e estilo da IA (ex: 'Positivo, Ajudante, Empático').")),
                ('foto_ia', models.ImageField(blank=True, help_text='Foto ou avatar da personalidade da IA.', null=True, upload_to='ai_personalities/')),
                ('etica', models.FloatField(help_text='Nível de ética da IA (0.0 = sem ética, 1.0 = totalmente ético).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('empatia', models.FloatField(help_text='Nível de empatia da IA (0.0 = sem empatia, 1.0 = totalmente empático).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('restricoes', models.TextField(help_text='Restrições e regras comportamentais específicas.')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta personalidade está disponível para uso.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'personalidade IA',
                'verbose_name_plural': 'personalidades IA',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permite_coleta_dados', models.BooleanField(default=True, help_text='Se o usuário permite que suas conversas sejam usadas para melhorar o modelo.')),
                ('tema_escuro', models.BooleanField(default=False, help_text='Se o usuário prefere o tema escuro na interface.')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, help_text='Data e hora da última atividade do usuário.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='chat_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='chat_user_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da conversa.', primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Nova Conversa', help_text='Título da conversa para exibição na interface.', max_length=255)),
                ('temperatura', models.FloatField(default=0.7, help_text='Valor de temperatura usado para a geração de respostas (0.0 a 2.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('total_mensagens', models.IntegerField(default=0, help_text='Número total de mensagens nesta conversa.')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Número total de tokens utilizados nesta conversa.')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a conversa foi criada.')),
                ('modificado_em', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização da conversa.')),
                ('excluida', models.BooleanField(default=False, help_text='Indica se a conversa foi excluída (soft delete).')),
                ('excluida_em', models.DateTimeField(blank=True, help_text='Data e hora em que a conversa foi marcada como excluída.', null=True)),
                ('usuario', models.ForeignKey(help_text='O usuário proprietário desta conversa.', on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to=settings.AUTH_USER_MODEL)),
                ('modelo_ia', models.ForeignKey(help_text='O modelo de IA usado nesta conversa.', on_delete=django.db.models.deletion.PROTECT, related_name='conversas', to='chat.modeloia')),
                ('personalidade', models.ForeignKey(help_text='A personalidade da IA usada nesta conversa.', on_delete=django.db.models.deletion.PROTECT, related_name='conversas', to='chat.personalidadeia')),
                ('personalidade_inicial', models.ForeignKey(blank=True, help_text='A personalidade da IA que iniciou a conversa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversas_iniciais', to='chat.personalidadeia')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'ordering': ['-modificado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a conversa foi utilizada para treinamento.')),
                ('modelo_destino', models.CharField(help_text='O modelo que foi treinado usando esta conversa.', max_length=50)),
                ('anonimizada', models.BooleanField(default=True, help_text='Se os dados pessoais foram removidos antes do treinamento.')),
                ('conversa', models.ForeignKey(help_text='A conversa utilizada para treinamento.', on_delete=django.db.models.deletion.CASCADE, related_name='historico_treinamento', to='chat.conversa')),
            ],
            options={
                'verbose_name': 'histórico de treinamento',
                'verbose_name_plural': 'históricos de treinamento',
                'ordering': ['-utilizado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Uma breve biografia sobre o usuário.')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil do usuário.', null=True, upload_to='profile_pics/')),
                ('data_aniversario', models.DateField(blank=True, help_text='Data de aniversário do usuário.', null=True)),
                ('usuario', models.OneToOneField(help_text='O usuário associado a este perfil.', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil do usuário',
                'verbose_name_plural': 'perfis dos usuários',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do plano (ex: 'Grátis', 'Pro', 'Premium').", max_length=50, unique=True)),
                ('descricao', models.TextField(help_text='Descrição detalhada dos benefícios do plano.')),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço mensal do plano em R$.', max_digits=10)),
                ('tokens_mensais', models.PositiveIntegerField(default=0, help_text='Número de tokens de IA incluídos por mês.')),
                ('limite_conversas', models.PositiveIntegerField(default=0, help_text='Limite de conversas ativas (0 = ilimitado).')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o plano está disponível para novas assinaturas.')),
                ('personalidades_exclusivas', models.ManyToManyField(blank=True, help_text='Personalidades de IA exclusivas para este plano.', to='chat.personalidadeia')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, help_text='Data de início da assinatura.')),
                ('data_renovacao', models.DateTimeField(help_text='Próxima data de renovação da assinatura.')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('pendente', 'Pendente'), ('expirada', 'Expirada')], default='ativa', help_text='Status atual da assinatura.', max_length=10)),
                ('data_cancelamento', models.DateTimeField(blank=True, help_text='Data em que a assinatura foi cancelada, se aplicável.', null=True)),
                ('usuario', models.OneToOneField(help_text='O usuário que possui esta assinatura.', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(help_text='O plano ao qual o usuário está assinado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.plano')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do pagamento.', max_digits=10)),
                ('data_transacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da transação.')),
                ('id_transacao_gateway', models.CharField(help_text='ID único da transação no gateway de pagamento (ex: Stripe).', max_length=255, unique=True)),
                ('status', models.CharField(help_text="Status da transação (ex: 'sucesso', 'falha', 'pendente').", max_length=50)),
                ('assinatura', models.ForeignKey(help_text='A assinatura à qual esta transação está vinculada.', on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='chat.assinatura')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='UsoDeTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(help_text='Mês e ano de referência para o consumo de tokens.', max_length=7)),
                ('tokens_consumidos', models.PositiveIntegerField(default=0, help_text='Total de tokens consumidos neste mês.')),
                ('usuario', models.ForeignKey(help_text='O usuário que consumiu os tokens.', on_delete=django.db.models.deletion.CASCADE, related_name='uso_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uso de token',
                'verbose_name_plural': 'uso de tokens',
                'ordering': ['-mes_ano'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da mensagem.', primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema'), ('tool', 'Ferramenta')], help_text='O papel de quem enviou a mensagem (user, assistant ou system).', max_length=10)),
                ('tipo_conteudo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('file', 'Arquivo')], default='text', help_text="Tipo de conteúdo da mensagem (ex: 'text', 'image').", max_length=10)),
                ('texto', models.TextField(blank=True, help_text='O conteúdo da mensagem.', null=True)),
                ('dados_conteudo', models.FileField(blank=True, help_text='O arquivo associado a esta mensagem, se houver.', null=True, upload_to='chat_uploads/')),
                ('tokens_utilizados', models.PositiveIntegerField(default=0, help_text='Número de tokens utilizados por esta mensagem.')),
                ('custo_estimado', models.DecimalField(decimal_places=6, default=0.0, help_text='Custo estimado desta mensagem (em dólares).', max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a mensagem foi criada.')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais em formato JSON.')),
                ('feedback', models.BooleanField(blank=True, help_text='Feedback do usuário sobre a mensagem (True = positivo, False = negativo).', null=True)),
                ('feedback_comentario', models.TextField(blank=True, help_text='Comentário adicional do usuário sobre o feedback.')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem da mensagem dentro da conversa.')),
                ('conversa', models.ForeignKey(help_text='A conversa à qual esta mensagem pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa')),
                ('parent_mensagem', models.ForeignKey(blank=True, help_text="Mensagem 'pai' para respostas alternativas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_alternativas', to='chat.mensagem')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['ordem'],
                'indexes': [models.Index(fields=['conversa', 'ordem'], name='chat_mensag_convers_28c9eb_idx'), models.Index(fields=['papel', 'criado_em'], name='chat_mensag_papel_2958e0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['usuario', 'modificado_em'], name='chat_conver_usuario_8a804b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['excluida', 'modificado_em'], name='chat_conver_excluid_24c0c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usodetokens',
            unique_together={('usuario', 'mes_ano')},
        ),
    ]
