# Generated by Django 5.2.4 on 2025-09-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalidadeia',
            name='modelo_ia',
            field=models.ForeignKey(blank=True, help_text='O modelo de IA associado a esta personalidade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalidades', to='chat.modeloia'),
        ),
    ]
