# Generated by Django 5.2.4 on 2025-09-17 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_personalidadeia_modelo_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='compartilhavel',
            field=models.BooleanField(default=False, help_text='Se a conversa pode ser acessada através de um link de compartilhamento público.'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='uuid_compartilhamento',
            # NOVO: O campo agora é adicionado com null=True para evitar o erro de integridade.
            # O `default` e o `unique` serão adicionados em uma migração posterior.
            field=models.UUIDField(default=None, null=True, editable=False, help_text='Identificador único e não adivinhavel para links de compartilhamento.'),
        ),
        # O índice pode ser adicionado agora sem problemas, pois não depende da unicidade dos dados.
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['uuid_compartilhamento'], name='chat_conver_uuid_co_0093b6_idx'),
        ),
    ]