# Generated by Django 5.2.4 on 2025-09-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_populate_uuids'),
    ]

    operations = [
    ]
